### ISSUE TITLE
with latest commit nvim-treesitter highlighting broken - `invalid node type at position .. for language jsonnet`

### ISSUE THREAD

**Issue by peterbueschel** [sourcegraph/tree-sitter-jsonnet#20]
Hi,

first thank you for this project.

with the latest update of the `jsonnet` parser in nvim-treesitter ([PR](https://github.com/nvim-treesitter/nvim-treesitter/commit/4ffdc4c985fb1054fb3bfa51c28917e2d9804ca3)) the highlight feature stopped working with the an error message similar to:
`invalid node type at position .. for language jsonnet`

![image](https://github.com/sourcegraph/tree-sitter-jsonnet/assets/5091565/e4900067-0502-4f82-be58-4c75b5aca9fb)

I am completely out of this parsing/query topic - but I tried to debug this a bit and find out that some changes made in the mentioned [PR](https://github.com/nvim-treesitter/nvim-treesitter/commit/4ffdc4c985fb1054fb3bfa51c28917e2d9804ca3) are the reason for this.

I manually commented out the parts in the [queries/jsonnet/highlights.scm](https://github.com/nvim-treesitter/nvim-treesitter/commit/4ffdc4c985fb1054fb3bfa51c28917e2d9804ca3#diff-ead5f0b76f79edbf8896d78ca71a7c6d126333e71d56ac94a7a6c4f8d6c237f8), which breaks the nvim-treesitter - and afterwards the highlight worked again:

[[13-17](https://github.com/nvim-treesitter/nvim-treesitter/blob/4ffdc4c985fb1054fb3bfa51c28917e2d9804ca3/queries/jsonnet/highlights.scm#L13-L17)]
```
(fieldaccess
  last: (id) @field)
(fieldaccess_super
  (id) @field)
```
[[line 42-43](https://github.com/nvim-treesitter/nvim-treesitter/blob/4ffdc4c985fb1054fb3bfa51c28917e2d9804ca3/queries/jsonnet/highlights.scm#L42-L43)]
```
(binary
  operator: (_) @operator)
```

[[line 82-89](https://github.com/nvim-treesitter/nvim-treesitter/blob/4ffdc4c985fb1054fb3bfa51c28917e2d9804ca3/queries/jsonnet/highlights.scm#L83-L89)]
```
(functioncall (id) @function.call)
(functioncall
  (fieldaccess
    last: (id) @function.call))
(functioncall
  (fieldaccess_super
    (id) @function.call))
```

So it looks like the new (not sure if this is the correct phrase) functions are somehow unknown. I checked my local files in the nvim-treesitter folder (using the master branch - lastest commit there):
- `./parser-info/jsonnet.revision`
- `./parser/jsonnet.so`
- `lockfile.json`

and all are related to   "jsonnet": { "revision": "d34615fa12cc1d1cfc1f1f1a80acc9db80ee4596"  } - So, the lastest commit in this repo here.

So, I hope someone can have a look or point me to right direction.

Thank you.

**Comment by 0x0013** [comment]
I am observing the same issue.

**Comment by peterbueschel** [comment]
Hi again,

it looks like the issue was caused by the https://github.com/HiPhish/rainbow-delimiters.nvim plugin - they [updated the queries](https://github.com/HiPhish/rainbow-delimiters.nvim/commit/c9e1442a09cc7677cf0a5ab57d81a5768438b600) on their end and now everything works as expected.

Means we latest version of nvim-treesitter + rainbow-delimiters.nvim everything is fine.
