### ISSUE TITLE
Directions for use with neovim

### ISSUE THREAD

**Issue by jessebye** [sourcegraph/tree-sitter-jsonnet#3]
Hey there, I'm just getting up to speed with using neovim and treesitter and found this when looking for jsonnet syntax support. I'd love to try it out but I'm not familiar enough with neovim/treesitter to know how to do that. Would it be possible to get simple instructions added to the README on how to use this?

**Comment by unrealhoang** [comment]
I think he will release a neovim plugin for jsonnet separately later, but for now you can do something like this to get the parser up and working:
1. Add Parser config for jsonnet:
```
  local parser_configs = require('nvim-treesitter.parsers').get_parser_configs()
  parser_configs.jsonnet = {
    install_info = {
      url = "https://github.com/sourcegraph/tree-sitter-jsonnet",
      files = { "src/parser.c", "src/scanner.c" },
      branch = "main"
    },
  }
```
2. Install parser:
```
:TSInstall jsonnet
```
3. Copy [`queries/highlights.scm`](https://github.com/sourcegraph/tree-sitter-jsonnet/blob/main/queries/highlights.scm) to `$HOME/.config/nvim/queries/jsonnet/highlights.scm`.
4. Set filetype to jsonnet: `:set ft=jsonnet`

**Comment by jessebye** [comment]
@unrealhoang thanks! I was successful in getting the parser to work, although syntax highlighting is not working for some reason. I can definitely live without that for now 😄

**Comment by graelo** [comment]
Thanks @unrealhoang!

@jessebye did you try to move `highlights.scm` to `$HOME/.config/nvim/after/queries/jsonnet/highlights.scm`? That where my highlights get picked up.

While I'm at it, if you want to set the `ft` automatically, one way is to use this (in a recent neovim, details [here](https://www.reddit.com/r/neovim/comments/rvwsl3/introducing_filetypelua_and_a_call_for_help/))

```lua
vim.filetype.add({
  filename = {
    ["MLproject"] = "yaml",
  },
  pattern = {
    [".*%.ssh/.*/config"] = "sshconfig",
    [".*%.jsonnet"] = "jsonnet",
  }
})
```

**Comment by jessebye** [comment]
@graelo yeah, I tried putting the `highlights.scm` there, but it appears that isn't used. I'm using lunarvim, which could have something to do with that... not sure where it parses highlights from.

I was setting the ft with this, which seemed to work OK:
```
vim.api.nvim_create_autocmd("BufEnter", {
  pattern = { "*.libsonnet" },
  command = "set filetype=jsonnet"
})
```
I wonder if there's any benefit to the approach you recommended?

**Comment by graelo** [comment]
@jessebye, that might be the cause, indeed, but I'm not familiar with lunarvim.

The neovim devs are pushing this new approach because it is faster and more concise, but caveat: it's in feature preview / beta. I just have a few filetypes, so there was no cost for me in adopting their proposal.
