### ISSUE TITLE
Calls with more than 2 arguments are not handled

### ISSUE THREAD

**Issue by aryx** [sourcegraph/tree-sitter-jsonnet#5]
The grammar hardcoded Calls with one or two arguments, but does not allow more.
We should use some repeat() in the grammar.

**Comment by aryx** [comment]
@tjdevries are you accepting pull requests for this repository, or this project is unmaintained and I should create a fork instead?

**Comment by tjdevries** [comment]
You can create a PR! Sorry, I was on paternity leave during October, so I completely missed this. I'll gladly review!

**Comment by aryx** [comment]
Fantastic! And congrats for the kid (and good luck ...).
I'll try to make a PR in the next few weeks.

**Comment by aryx** [comment]
As an example of this issue, the tree-sitter-jsonnet parser can't parse std.jsonnet, the official
standard library: https://github.com/google/jsonnet/blob/master/stdlib/std.jsonnet
